export { Client, CographError, RawApi, USER_SCHEDULABLE_ACTIONS } from "./client.js";
export type {
  ClientOptions,
  IngestOptions,
  AskOptions,
  AgentTurnOptions,
  AgentResult,
  ResolvedChange,
  OntologyResolveResult,
  OntologyApplyResult,
  EnrichRequest,
  EnrichJob,
  EnrichJobCreate,
  JobProgress,
  JobSummary,
  Verdict,
  ConflictReview,
  RowResult,
  EnrichmentTier,
  JobStatus,
  ConflictPolicy,
  RowAction,
  ReviewDecision,
  // COG-128 — raw/passthrough API + newly-added typed shapes
  RawInit,
  TypeRecord,
  TypeRecordsPage,
  TypeEdge,
  NormalizationRule,
  // ONTA-178 — canonical semantic instance search
  SemanticSearchHit,
  SemanticSearchResponse,
  // ONTA-173 — schedules: user-schedulable vs system-managed action split
  Schedule,
  ScheduleAction,
  UserSchedulableAction,
} from "./client.js";
