"""Semantic instance index — models + swappable backend Protocol (ONTA-175).

Neptune (our RDF source of truth) has **no full-text or vector index**: answering
"which entities talk about supply-chain resilience?" against Neptune means
scanning every free-text literal and post-filtering, which does not scale. This
module adds a **secondary index over marked free-text instance attributes**
(description, bio, notes, …): each (entity, attribute) document is canonicalized,
chunked (~256–512 tokens) and indexed so a hybrid lexical + vector query returns
entity URIs (+ denormalized display ``attrs`` and a matching snippet) in a
single hop with **no Neptune round-trip**.

Design (mirrors ``spatiotemporal/`` — the existing swappable-backend pattern:
``JobStore`` / ``VerdictStore`` / ``SpatioTemporalIndex`` + ``register_*``):

* :class:`SemanticIndex` is a ``Protocol`` so the backend is pluggable.
* :class:`InMemorySemanticIndex` (``memory.py``) is the zero-config OSS default —
  pure Python + numpy, fully functional for tests and Postgres-less OSS use.
* ``PostgresSemanticIndex`` (ONTA-176, the next sub-issue — deliberately NOT in
  this tree yet) will be the durable pgvector adapter over the generic
  ``settings.database_url`` DSN: one ``entity_semantic_chunk`` table with a
  GENERATED ``tsvector`` column (lexical) and a nullable ``vector(1536)``
  column (ANN), hybrid-queried in one SQL round-trip fused via RRF (k=60).

Consistency model (ONTA-173 design record)
------------------------------------------

Neptune stays the **source of truth**; this index is a DERIVED companion store
(exactly like the spatio-temporal index and the provenance graph). Two
independent mechanisms keep it fresh AND correct::

    writers                 +---------------------------+
    (ingest, enrichment, -->| insert_facts (kg_writer)  |--> Neptune
     normalize, dedupe)     +------------+--------------+    (source of truth)
                                         |                        |
                   sync write hook       |                        |  hourly + on-demand
                   (ONTA-181):           |                        |  scan of marked attrs
                   extract -> upsert;    |                        v
                   rows land with        |          +---------------------------+
                   embedding=NULL,       |          |  reconciler (ONTA-181)    |
                   tsvector GENERATED    |          |  claim-based:             |
                   -> lexical search     |          |  - upsert by content_hash |
                   works instantly       |          |  - delete ghosts (ER      |
                                         v          |    merges / normalization |
                     +--------------------------+   |    deletes bypass hook)   |
                     | semantic index (derived) |<--|  - apply candidacy flips  |
                     |  entity_semantic_chunk   |   |  - first run = backfill   |
                     +------------+-------------+   +---------------------------+
                                  |
                                  |  embedding IS NULL == the durable queue
                                  |  (no outbox table)
                                  v
                     +--------------------------+
                     | embed-fill sweep (~5min) |
                     | fetch_pending -> shared  |
                     | embed client (ONTA-174)  |
                     | -> fill_embeddings       |
                     |    (stamps embed_model)  |
                     +--------------------------+

* **Freshness** comes from a synchronous write hook in
  ``graph.kg_writer.insert_facts`` (ONTA-181, not built here): chunk + hash rows
  land in the same request that wrote Neptune, with ``embedding=NULL``. The
  ``tsvector`` is generated by the store, so *lexical* search over new facts
  works instantly; vector recall follows within one sweep interval.
* **Correctness** comes from a claim-based reconciler (ONTA-181): (1) an
  embed-fill sweep (~5 min) drains NULL embeddings via the shared embed client
  (``nlp.embed_client``, ONTA-174); (2) an hourly + on-demand Neptune scan of
  the marked attributes upserts by ``content_hash``, deletes ghosts (ER merges
  and normalization deletes bypass the write hook), and applies candidacy
  flips (an attribute marked/unmarked after data already landed). The first
  reconciler run doubles as the backfill.
* The NULL ``embedding`` column IS the durable queue — there is no outbox
  table to keep transactional with the chunk rows, no second source of truth
  about "what still needs embedding".
"""

from __future__ import annotations

from typing import Any, Optional, Protocol, Sequence, runtime_checkable

from pydantic import BaseModel, Field

#: The primary key of one chunk row: ``(tenant_id, kg_name, entity_uri, attr,
#: chunk_ix)``. ``(tenant_id, kg_name)`` is the isolation boundary (same
#: semantics as the spatio-temporal index — ``tenant_id`` alone is never
#: enough); ``(entity_uri, attr)`` identifies the source document; ``chunk_ix``
#: is the 0-based position of this chunk within it.
ChunkKey = tuple[str, str, str, str, int]


class SemanticChunk(BaseModel):
    """One indexed chunk of an (entity, attribute) free-text document.

    Mirrors one row of the ONTA-176 ``entity_semantic_chunk`` table (minus the
    GENERATED ``tsv`` column, which only exists store-side), keyed
    ``(tenant_id, kg_name, entity_uri, attr, chunk_ix)``:

    * ``kg_name`` scopes the chunk to ONE knowledge graph within the tenant —
      dropping a single KG must clear only its chunks, never a sibling KG's,
      and a query may be narrowed to one KG (same rationale as
      ``SpatioTemporalFact.kg_name``).
    * ``attr`` is the marked predicate's local name (e.g. ``description``) —
      the *document* unit: all values of one attribute on one entity are
      canonicalized into a single doc, then chunked.
    * ``content_hash`` is the sha256 of the CANONICALIZED FULL DOC for this
      (entity, attr) — every chunk of the doc carries the same hash. It is the
      change-detection currency of the whole subsystem: the write hook skips
      an unchanged hash, the reconciler upserts by it, and the embed-fill
      sweep uses it as an optimistic-concurrency token (a fill for a row whose
      content changed mid-flight must not apply — see :meth:`SemanticIndex.fill_embeddings`).
    * ``embedding`` is ``None`` until the embed-fill sweep fills it — the NULL
      embedding IS the durable work queue (see the module docstring). When
      filled, ``embed_model`` records which model produced it, so a model
      upgrade can invalidate/re-embed selectively.
    * ``attempt_count`` / ``last_error`` are the sweep's backoff / dead-letter
      bookkeeping (ONTA-176 columns), advanced via :meth:`SemanticIndex.mark_embed_failed`.
    * ``attrs`` holds **denormalized display fields** (label, type, …) so a hit
      renders without a Neptune round-trip. Keep it small — it is stored
      verbatim as ``jsonb`` and shipped on every hit. ``attrs["type"]`` is also
      the ``type_filter`` predicate at query time.
    """

    tenant_id: str
    kg_name: str
    entity_uri: str
    attr: str
    chunk_ix: int = Field(..., ge=0)
    chunk_text: str
    content_hash: str
    embedding: Optional[list[float]] = None
    embed_model: Optional[str] = None
    attempt_count: int = 0
    last_error: Optional[str] = None
    attrs: dict[str, Any] = Field(default_factory=dict)

    def key(self) -> ChunkKey:
        """This chunk's primary key (see :data:`ChunkKey`)."""
        return (
            self.tenant_id,
            self.kg_name,
            self.entity_uri,
            self.attr,
            self.chunk_ix,
        )

    def doc_key(self) -> tuple[str, str, str, str]:
        """The (entity, attr) *document* this chunk belongs to — the unit that
        replace-on-upsert and ghost-deletion operate on."""
        return (self.tenant_id, self.kg_name, self.entity_uri, self.attr)


class SemanticHit(BaseModel):
    """A single entity-grouped search hit.

    Chunks are scored individually but results are **grouped by entity** (the
    caller asked "which entities…", not "which chunks…"): the entity's score is
    its best chunk's fused score, and ``snippet`` / ``attr`` come from that best
    chunk so the UI can show *where* the match happened. Deliberately does NOT
    carry the full chunk list back — the index is a *finder*; hydration of full
    entities from Neptune (if needed) is the caller's concern (same contract as
    ``STQueryResult``).
    """

    entity_uri: str
    attrs: dict[str, Any] = Field(default_factory=dict)
    snippet: str = ""
    attr: str = ""
    score: float = 0.0


class SemanticSearchResult(BaseModel):
    """The result envelope for :meth:`SemanticIndex.search`.

    ``degraded`` is ``True`` when the query ran **lexical-only** because no
    query embedding was available (embedding service down / unconfigured — the
    ONTA-176 degraded mode). Surfaced explicitly, never silently: callers (API
    routes, MCP tools) propagate it so a UI can badge "reduced recall" instead
    of users mistaking a degraded answer for a complete one.
    """

    hits: list[SemanticHit] = Field(default_factory=list)
    degraded: bool = False


@runtime_checkable
class SemanticIndex(Protocol):
    """Swappable semantic instance index over (entity, attr) text chunks.

    All methods are ``async``. Queries are always scoped to a single
    ``tenant_id`` (tenant isolation is mandatory — a query MUST NEVER cross
    tenants) and may be further narrowed to one ``kg_name`` (``None`` = every
    KG in the tenant) — identical semantics to :class:`~cograph_client.spatiotemporal.protocol.SpatioTemporalIndex`.

    Premium/alternate backends implement these and register via
    :func:`cograph_client.semantic.registry.register_semantic_index`.
    """

    async def upsert_chunks(self, chunks: Sequence[SemanticChunk]) -> None:
        """Idempotently upsert chunk rows, replacing each (entity, attr) doc.

        **Complete-document contract:** callers pass ALL chunks of each
        (entity, attr) doc they touch — exactly what
        :func:`cograph_client.semantic.extract.extract_semantic_chunks`
        produces (contiguous ``chunk_ix`` from 0). Within each doc:

        * a row whose PK exists with the SAME ``content_hash`` keeps its
          text/hash/embedding/queue state as-is — crucially preserving an
          already-filled embedding, so replaying an unchanged doc never
          re-queues embedding work (idempotent replay) — but its denormalized
          ``attrs`` are **always refreshed** from the incoming chunk: type and
          label can change while the marked text does not (ER retype,
          enrichment filling a label), and the display attrs must track the
          entity, not the text (this is what makes the ONTA-181 reconciler an
          actual corrective for the documented type-filter staleness);
        * a row whose PK exists with a DIFFERENT ``content_hash`` is replaced
          (embedding reset per the incoming chunk, normally ``None`` → queued);
        * rows with ``chunk_ix`` beyond the incoming doc's highest index are
          **deleted** — the stale tail when a doc shrank (ONTA-181's
          fewer-chunks-than-before case).

        To remove a doc entirely (attribute now empty / unmarked), use
        :meth:`delete` with ``attr=…`` — an empty doc has no chunk rows to
        carry its key here.
        """
        ...

    async def search(
        self,
        tenant_id: str,
        query_text: str,
        *,
        query_embedding: Optional[Sequence[float]] = None,
        kg_name: Optional[str] = None,
        type_filter: Optional[str] = None,
        top_k: int = 10,
    ) -> SemanticSearchResult:
        """Hybrid lexical + vector search, grouped by entity.

        Candidates are pre-filtered by ``tenant_id`` (mandatory), ``kg_name``
        (``None`` = all KGs in the tenant) and ``type_filter`` (matched against
        the denormalized ``attrs["type"]`` — ONTA-176 filters ``attrs->>'type'``
        the same way). Lexical and vector rankings are fused RRF-style (the
        pgvector backend: two top-50 CTEs, k=60, one SQL round-trip), chunks are
        grouped into entities, and the ``top_k`` best entities come back.

        ``query_embedding=None`` → **lexical-only** and
        ``SemanticSearchResult.degraded`` is ``True`` (never silent). Callers
        embed the query via the shared embed client and pass the vector in —
        the index itself never calls an embedding API.
        """
        ...

    async def delete(
        self,
        entity_uri: str,
        tenant_id: str,
        *,
        kg_name: Optional[str] = None,
        attr: Optional[str] = None,
    ) -> None:
        """Remove chunks for one entity. ``kg_name`` narrows to a single KG
        (``None`` = every KG in the tenant); ``attr`` narrows to a single
        (entity, attr) doc (``None`` = all of the entity's docs).

        ``attr=…`` is the reconciler's ghost-deletion / doc-now-empty primitive
        (ONTA-181); bare ``delete(uri, tenant)`` is the ER-merge / entity-delete
        path.
        """
        ...

    async def clear(self, tenant_id: str, *, kg_name: Optional[str] = None) -> None:
        """Remove chunks for a tenant. ``kg_name`` clears just that KG (the
        KG-delete path); ``None`` clears the whole tenant (tenant teardown)."""
        ...

    # -- doc enumeration (ONTA-181's reconciler ghost diff) -------------------

    async def list_docs(
        self, tenant_id: str, *, kg_name: Optional[str] = None
    ) -> list[tuple[str, str, str, dict[str, Any]]]:
        """Enumerate indexed documents as ``(entity_uri, attr, content_hash,
        attrs)`` rows — one row per (entity, attr) **document**, never per
        chunk. ``attrs`` is the doc's stored denormalized display attrs, taken
        from its chunk-0 row (every chunk of a doc carries the same attrs when
        written through :meth:`upsert_chunks`).

        The consumer is the ONTA-181 reconciler's claim diff: it compares this
        listing against what a fresh Neptune scan says SHOULD be indexed to
        (a) DELETE ghosts — docs whose (entity, attr) no longer exists in
        Neptune because an ER merge or a normalization delete bypassed the
        write hook — (b) SKIP re-upserting unchanged docs (the
        ``skipped_unchanged_hash`` counter), and (c) REPAIR docs whose text is
        unchanged but whose denormalized ``attrs`` drifted (type/label changed
        without the marked text changing — the ``attrs_repaired`` counter).
        Doc granularity is what makes all three cheap: ``content_hash`` is the
        sha256 of the canonicalized FULL doc, identical across every chunk of
        the doc **by construction** (see :class:`SemanticChunk`), and ``attrs``
        is small by contract, so the doc-level row is complete change-detection
        currency without shipping chunk rows or text — in ONE round trip.

        Scoping is identical to :meth:`search` / :meth:`clear`: ``tenant_id``
        is mandatory (a listing MUST NEVER cross tenants), ``kg_name`` narrows
        to one KG (``None`` = every KG in the tenant). The result is ordered
        deterministically (sorted by ``(entity_uri, attr)``, which is unique
        per doc) so reconciler runs and parity tests are reproducible across
        backends.

        HISTORY: this started as an OPTIONAL duck-typed seam returning
        3-tuples because the Protocol was frozen while ONTA-181 was built. It
        is now part of the Protocol — both first-party backends implement the
        4-tuple form — but the reconciler still looks it up with ``getattr``
        and degrades gracefully: a missing method skips ghost repair (loudly
        logged); a legacy 3-tuple listing still gets hash-diffing, only the
        attrs-repair pass is skipped.
        """
        ...

    async def delete_docs(
        self,
        pairs: Sequence[tuple[str, str]],
        tenant_id: str,
        *,
        kg_name: str,
    ) -> None:
        """Remove the ``(entity_uri, attr)`` docs in ``pairs`` from ONE KG, in
        one batched call.

        The reconciler's ghost-deletion primitive (ONTA-181): a reconcile of a
        KG that lost many entities to an ER rebuild would otherwise issue one
        :meth:`delete` round trip per ghost doc. Semantically identical to
        calling ``delete(entity_uri, tenant_id, kg_name=…, attr=…)`` per pair
        — same scoping rules (``tenant_id`` mandatory; ``kg_name`` REQUIRED
        here because ghost diffs are always per-KG). An empty ``pairs`` is a
        no-op. Third-party backends that predate the method degrade via the
        reconciler's per-doc :meth:`delete` fallback; :meth:`delete` itself
        remains the write hook's single-doc primitive.
        """
        ...

    # -- embed-fill sweep seam (ONTA-181's reconciler drives these) ----------

    async def fetch_pending(
        self,
        *,
        limit: int = 100,
        max_attempts: Optional[int] = None,
        tenant_id: Optional[str] = None,
        kg_name: Optional[str] = None,
    ) -> list[SemanticChunk]:
        """Fetch up to ``limit`` chunks awaiting embedding (``embedding IS NULL``).

        The NULL embedding column is the durable queue (module docstring), so
        this is literally "SELECT … WHERE embedding IS NULL LIMIT n" — in a
        deterministic order so concurrent sweeps make forward progress.
        ``max_attempts`` skips rows already tried that many times (the
        dead-letter cutoff — they stay visible via higher ``max_attempts`` /
        ``None`` for ops inspection, never silently vanish).

        MAINTENANCE-ONLY exception to tenant scoping: ``tenant_id=None`` spans
        all tenants because the sweep is a process-wide background worker, not
        a user query. Never expose this path to request handlers.
        """
        ...

    async def fill_embeddings(
        self,
        chunks: Sequence[SemanticChunk],
        embeddings: Sequence[Sequence[float]],
        *,
        embed_model: str,
    ) -> int:
        """Fill embeddings for ``chunks`` (parallel to ``embeddings``); returns
        the number of rows actually updated.

        Callers pass back the exact chunks they got from :meth:`fetch_pending`;
        each row is updated ONLY IF it still exists with the same
        ``content_hash`` and its embedding is still NULL — the hash is the
        optimistic-concurrency token guarding against the write hook replacing
        the doc between fetch and fill (a stale vector for new text must never
        land). Stamps ``embed_model`` and clears ``last_error`` on success.
        """
        ...

    async def mark_embed_failed(
        self, chunks: Sequence[SemanticChunk], *, error: str
    ) -> int:
        """Record an embedding failure for ``chunks``; returns rows updated.

        Increments ``attempt_count`` and sets ``last_error`` (same
        content-hash guard as :meth:`fill_embeddings`), leaving the embedding
        NULL so the row stays queued until ``max_attempts`` dead-letters it.
        The sweep's backoff policy lives in the reconciler (ONTA-181), not
        here — the index only keeps the counters durable.
        """
        ...
